---

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Node.js
        uses: actions/setup-node@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Pip Packages
        run: |-
          pip install -U -r requirements.txt
          pip install -U mypy types-Markdown
          pip install -U setuptools wheel

      - name: Install NPM Packages
        run: npm install

      - name: Build
        run: ./build.py

      - name: Release
        run: ./setup.py sdist bdist_wheel
