---

name: R

on:
  push:
    paths:
      - "setup.py"

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Node.js
        uses: actions/setup-node@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Pip Packages
        run: |-
          pip install -U -r requirements.txt
          pip install -U mypy
          pip install -U setuptools wheel

      - name: Install NPM Packages
        run: npm install

      - name: Build
        run: ./build.py

      - name: Release
        run: ./setup.py sdist bdist_wheel

      - name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
